### ISSUE TITLE
also set background-color if color is set

### ISSUE THREAD

**Issue by imme-emosol** [chaselambda/makefiletutorial#15]

**Comment by chaselambda** [comment]
What's the issue here? I also recently redesigned the website so I'm guessing this isn't an issue anymore, but let me know

**Comment by imme-emosol** [comment]
![Screenshot_2020-12-28_13-53-09](https://user-images.githubusercontent.com/487989/103215735-86857980-4914-11eb-9432-872b9603e0b9.png)

**Comment by chaselambda** [comment]
Oh how did you make this happen?

**Comment by imme-emosol** [comment]
The default colors in my browser are with a dark(er) background (and contrasting font-color) as I find that easier to read.
I know this is not standard but it is something that happens. So, the assumption that a <body>'s default background-color is white does not hold true.

While we are having this conversation anyway;
I would like to point out that there is a css way to style a page differently based on the user-agent's preference.
`prefers-color-scheme`

**Comment by chaselambda** [comment]
I'm still a bit confused. Do you have a browser extension that does this for you? I'm on MacOS in dark mode and my website looks the same. I don't intend to add dark mode support any time soon -- even if dark mode is on for you I intend for the website to just be the same.

**Comment by imme-emosol** [comment]
In Firefox Preferences, under Language and Appearance - Fonts and Colors I changed the default colors for pages.

Since your stylesheet does not define a background-color for either the html or body tag, it uses that default background-color that I configured.
