### ISSUE TITLE
The headings don't really make any sense

### ISSUE THREAD

**Issue by crccheck** [chaselambda/makefiletutorial#2]
Looking at http://makefiletutorial.com/, There are seven "Intro" headings and then monotone increasing numbers: 2.4, 2.5, 4.1, 4.2, 4.2.3, etc...

What was the intent?

**Comment by jaxxstorm** [comment]
+1

**Comment by goog** [comment]
site seems broken.

**Comment by NSExceptional** [comment]
Yo @theicfire, you alive? I'll fix this if you'll actually merge a PR.

**Comment by chaselambda** [comment]
Oh man, I missed these comments. Thanks @NSExceptional for the @ mention.
The headings are coming from the GNU Make book: https://www.gnu.org/software/make/manual/make.pdf

I can definitely make this more clear, I'll take a look this weekend!

**Comment by chaselambda** [comment]
Fixed, thanks and apologies for the delay!
