### ISSUE TITLE
Thank-you for plagiarising my makefile tutorial and leaving no attribution.

### ISSUE THREAD

**Issue by ArashPartow** [chaselambda/makefiletutorial#21]

**Comment by chaselambda** [comment]
I think you're referring to https://www.partow.net/programming/makefile/index.html. I diligently wrote everything else in the tutorial.

I had temporarily put up an example that was indeed derived from the above page (10 days ago). I should have attributed that to you, sorry about that. I've gone ahead and removed it, as I was able to find another example that I preferred. Thanks!
