### ISSUE TITLE
Specify Make Version

### ISSUE THREAD

**Issue by tajmone** [chaselambda/makefiletutorial#26]
Great tutorial!

I suggest adding right at the beginning which major make version the tutorial targets — i.e. v3 or v4?

One of the most confusing aspects of make to me is that some projects rely on make v3.x, while others rely on v4.x, which introduces some syntax incompatibility issues — especially under Windows, where the official make for Windows from GNU is still v3, whereas the version bundled with MinGW is v4 (`mingw32-make.exe`). 

Unfortunately. most make tutorials omit mentioning the version they are targeting.

By stating right at the beginning which make version the tutorial was written for could avoid confusion right away.

Also, it might be worth spending a few paragraphs on the differences between make v3 and v4 and the fact that they are both currently used by many projects — and maybe also mention they key aspects in which they differ and how to write Makefiles that would work with both version?

I still don't know what they key differences between these two major versions are, and their coexistence in everyday use has been an obstacle in learning Make, which is why I'd definitely appreciate a tutorial which explains the issue (couldn't easily find a dedicated article on this).

**Comment by chaselambda** [comment]
Ah thanks! It looks like the changelist for each version is listed here http://savannah.gnu.org/news/?group=make (each version has to be downloaded and the `NEWS` file has the changelist).

From some brief searching, the changes from 3.81 -> 3.82 seem to be the main backwards incompatibility changes.

I had thought all of these worked for Make 4.1+, do you remember the ones that seemed to rely on v3.x?

**Comment by tajmone** [comment]
> It looks like the changelist for each version is listed here http://savannah.gnu.org/news/?group=make (each version has to be downloaded and the NEWS file has the changelist).

That link might be worth adding to the tutorial.

> I had thought all of these worked for Make 4.1+, do you remember the ones that seemed to rely on v3.x?

No I haven't tried them all of them out. But from a practical experience, when cloning a repository that uses Make, it will be either using Make 3 or Make 4, so I keep on my machine the latest version available of both major versions.

I'm not sure why some projects are still using Make 3, i.e. whether it's because they don't want to migrate to v4 just because the benefits are not worth the effort, or because the majority of the projects in the wild are still using Make 3, or whatever other reason. But I personally think that it would be nice if the tutorial mentioned the fact that presently both versions are still widely used, explaining the historical reasons, etc., thus preparing the reader for real life scenarios.

For some reason, most Make tutorials I've come across don't mention the Make version they were written for. I guess that some of them were written before Make 4 was released, so they didn't deem it necessary to make the distinction, while Make 4 tutorials might be giving for granted that the reader will be using the latest version.

**Comment by chaselambda** [comment]
Awesome I appreciate the thorough response. I'll think about what to do here

**Comment by chaselambda** [comment]
Fixed in https://github.com/theicfire/makefiletutorial/commit/dcfb44a2493270e6f4181946c5ffa392bbca813f
