### ISSUE TITLE
Automatic variables $? is newer not older

### ISSUE THREAD

**Issue by mishinma** [chaselambda/makefiletutorial#27]
Hi, awesome tutorial!

I noticed a little typo: the comment for `$?` should be "Outputs all prerequisites *newer* than the target"
![image](https://user-images.githubusercontent.com/8950027/107764334-b360e500-6d38-11eb-941f-ac8dcb4017d0.png)

Cheers,
Misha

**Comment by chaselambda** [comment]
Ah thank you, fixed!
