### ISSUE TITLE
Add example for "Arguments to Specify the Goals"

### ISSUE THREAD

**Issue by roukmoute** [chaselambda/makefiletutorial#28]
It could be great to adding an example for "MAKECMDGOALS": https://www.gnu.org/software/make/manual/html_node/Goals.html

**Comment by chaselambda** [comment]
The command seems a bit rare to me. Do you have some use cases where you find it to be particularly useful? Or, what made you think of this command in the first place when you were reading the tutorial?

The linked example seems to be using MAKECMDGOALS only as an optimization -- to speed up `make clean`. Optimizations like that seem to esoteric to fit into a brief reference manual/tutorial
