### ISSUE TITLE
Request pdf and epub output

### ISSUE THREAD

**Issue by mmdbalkhi** [chaselambda/makefiletutorial#29]
# Request pdf and epub output
Hello, thank you for your training.  If possible, please insert the **pdf** and **epub** output.  Unfortunately, the system browser cannot print properly from the site.

**Comment by chaselambda** [comment]
What's the issue? It looks mostly fine to me:
![image](https://user-images.githubusercontent.com/442311/113176686-9b1e2a00-9201-11eb-839b-dde63fc3093c.png)

**Comment by chaselambda** [comment]
In fact here's a pdf: 
[makefiletutorial.pdf](https://github.com/theicfire/makefiletutorial/files/6237947/makefiletutorial.pdf)

**Comment by mmdbalkhi** [comment]
Hi sir.  Unfortunately, some code or text is split between pages and is difficult to read.  Thanks again for your efforts

**Comment by chaselambda** [comment]
Got it, I think unfortunately I won't be prioritizing this but I appreciate the comments
