### ISSUE TITLE
Point out that this is GNU make

### ISSUE THREAD

**Issue by cvengler** [chaselambda/makefiletutorial#34]
Hello, first this site is an awesome tutorial.

However, it doesn't point out the fact that functions like wildcard are exclusive to GNU make and won't work on BSD make for example.

I suggest adding a note on the top that this assumes GNU make which might be available in your packages/ports as `gmake` and you should go for that instead if certain examples don't work.

**Comment by chaselambda** [comment]
Fixed in https://github.com/theicfire/makefiletutorial/commit/dcfb44a2493270e6f4181946c5ffa392bbca813f
