### ISSUE TITLE
Error in cookbook example

### ISSUE THREAD

**Issue by yhshin11** [chaselambda/makefiletutorial#36]
Website's very helpful, but I think there's an error in the cookbook example that should be fixed:
```
SRCS := $(shell find $(SRC_DIRS) -name *.cpp -or -name *.c)
```
`*.cpp` and `*.c` should be wrapped in single quotes, or GNU make will expand the wildcard expression before passing to `find`, which is unintended.

If you have a single `.cpp` file, you'll be running `find ./src -name foobar.cpp`, which will most likely only return that one file.
If you have multiple files with the `.cpp` extension, you'll be passing multiple files after `-name` to `find`, e.g. `find ./src -name foo.cpp bar.cpp` and it will throw an error like this:

```
find: paths must precede expression: `bar.cpp'
find: possible unquoted pattern after predicate `-name'?
```

If you go to the bottom of the comments where the example was pulled, you'll find someone who encountered this exact issue:  
https://spin.atomicobject.com/2016/08/26/makefile-c-projects/

**Comment by chaselambda** [comment]
Nice catch, fixed, thank you very much!
