### ISSUE TITLE
Static Pattern Rules and Filter --- errors: are they intentional

### ISSUE THREAD

**Issue by tiborh** [chaselambda/makefiletutorial#40]
When trying this in a Makefile:

> obj_files = foo.result bar.o lose.o
> src_files = foo.raw bar.c lose.c
> 
> all: $(obj_files)
> 
> $(filter %.o,$(obj_files)): %.o: %.c
>     echo "target: $@ prereq: $<"
> $(filter %.result,$(obj_files)): %.result: %.raw
>     echo "target: $@ prereq: $<" 
> 
> %.c %.raw:
>     touch $@
> 
> clean:
>     rm -f $(src_files)`

I get the following output:

> $ make
> touch foo.raw
> echo "target: foo.result prereq: foo.raw" 
> target: foo.result prereq: foo.raw
> touch bar.c
> echo "target: bar.o prereq: bar.c"
> target: bar.o prereq: bar.c
> touch lose.c
> echo "target: lose.o prereq: lose.c"
> target: lose.o prereq: lose.c
> touch all.c
> cc    -c -o all.o all.c
> cc   all.o foo.result bar.o lose.o   -o all
> cc: error: foo.result: No such file or directory
> cc: error: bar.o: No such file or directory
> cc: error: lose.o: No such file or directory
> make: *** [<builtin>: all] Error 1
> rm all.o all.c

Is this intended output?

**Comment by chaselambda** [comment]
Oof! Try adding `.PHONY: all` above the `all:` line. Like this:

```
obj_files = foo.result bar.o lose.o
src_files = foo.raw bar.c lose.c

.PHONY: all
all: $(obj_files)

$(filter %.o,$(obj_files)): %.o: %.c
	echo "target: $@ prereq: $<"
$(filter %.result,$(obj_files)): %.result: %.raw
	echo "target: $@ prereq: $<"

%.c %.raw:
	touch $@

clean:
	rm -f $(src_files)
```

Does that fix it for you?

**Comment by chaselambda** [comment]
Should be fixed by https://github.com/theicfire/makefiletutorial/commit/e457b8d42ff37fda8a9571fe9caeda5722c5a536 unless you're also noticing a second issue here.

**Comment by tiborh** [comment]
Thank you. Yes, that solves it.
Output:
```
$ make
touch foo.raw
echo "target: foo.result prereq: foo.raw" 
target: foo.result prereq: foo.raw
touch bar.c
echo "target: bar.o prereq: bar.c"
target: bar.o prereq: bar.c
touch lose.c
echo "target: lose.o prereq: lose.c"
target: lose.o prereq: lose.c
```
Files in directory:
```
$ ls
bar.c  foo.raw  lose.c  Makefile
```
(`make clean` successfully restores original state)

**Comment by chaselambda** [comment]
Great, thanks for letting me know!
