### ISSUE TITLE
Error in multiple target eaxmple

### ISSUE THREAD

**Issue by Jimall** [chaselambda/makefiletutorial#44]
I think there is an error in multiple-targets chapter(https://makefiletutorial.com/#multiple-targets), miss `:` after f1.o and f2.o, here is the screenshot:

![image](https://user-images.githubusercontent.com/43246534/155647809-981817fd-ac05-488b-b22f-1d18e52caaff.png)

should be:
```Makefile
# f1.o:
#	 echo $@
# f2.o:
#	 echo $@
```

and I think this will be more clear to show `When there are multiple targets for a rule, the commands will be run for each target` and the meaning of `$@`:

```Makefile
# f1.o:
#	 echo f1.o
# f2.o:
#	 echo f2.o
```

**Comment by chaselambda** [comment]
Fixed, thank you! https://github.com/theicfire/makefiletutorial/commit/9dd3b615c991e4e5dac7bc732eb503e01cd86a7c
