### ISSUE TITLE
Beginner example still too complex

### ISSUE THREAD

**Issue by jxu** [chaselambda/makefiletutorial#52]
The beginner example is introduced with 3 rules. Following this dependency chain requires recursing two levels deep. I believe a simpler example would first introduce a trivial makefile with no dependency to get used to invoking compilation

```make
blah:
    cc -o blah blah.c
```

and then maybe just two rules with one dependency, for example

```make
blah: blah.o
	cc blah.o -o blah # Runs second

blah.o: blah.c
	cc -c blah.c -o blah.o # Runs first
```
where blah.c exists; the echo is confusing because blah.c source would normally exist already.

Also there should be a separator between examples since the article immediately jumps to a new example with "This makefile has a single target..."

**Comment by chaselambda** [comment]
Thank you for the nudge, should be solved! Please let me know if there's anything that's still unclear.

**Comment by jxu** [comment]
Yes, the new explanation of the purpose of makefiles helps tremendously. A few things:

- The code references file `foobar` but the target is called `hello`
- "commands" should not be in inline-code font
- I still think the echo C code into file is a little contrived for a tutorial but maybe other people can understand it well.

**Comment by chaselambda** [comment]
Fixed/clarified, thank you! https://github.com/theicfire/makefiletutorial/commit/5c03f15e074ac5cedbe3b4f0eba28d2f4b4ef409

**Comment by jxu** [comment]
After going through the tutorial again, I still think the echo into blah.c example is too contrived. What I suggested before is much more representative of a real project:

> and then maybe just two rules with one dependency, for example
> 
> ```makefile
> blah: blah.o
> 	cc blah.o -o blah # Runs second
> 
> blah.o: blah.c
> 	cc -c blah.c -o blah.o # Runs first
> ```
> 
> where blah.c exists; the echo is confusing because blah.c source would normally exist already.

We created blah.c previously in the tutorial too in "The essence of Make". I can open a PR if you'd like.

**Comment by jxu** [comment]
Maybe also worth mentioning for those that are familiar that makefiles are a form of declarative programming, in that the exact order of execution is not explicitly specified but figured out by the make implementation.

**Comment by chaselambda** [comment]
Thanks for the thoughts!

Although the example is contrived, I don't think it's confusing because of the comment. I think it's helpful to keep because people can easily delete `blah.c` and have it recreated quickly.

I think the "declarative programming" point does not help teach Makefiles. I think it helps people that might want to connect concepts together (useful!), but I have a strong value for the project of being as succinct as possible, so I'm ok with keeping these pieces out.
