### ISSUE TITLE
Static Pattern Rules and Filter -- Errors and naive fix

### ISSUE THREAD

**Issue by a1exlism** [chaselambda/makefiletutorial#60]
Issue: part `Static Pattern Rules and Filter` example not works well, refer to issue [40](https://github.com/theicfire/makefiletutorial/issues/40).

Refer issue [40](https://github.com/theicfire/makefiletutorial/issues/40) and the issue was fixed by commmit [b7e9438](https://github.com/theicfire/makefiletutorial/commit/b7e9438cef7d79d31fc1398fd4f886dc3b6d89d1).

However, the code was reversed after the `new design` commitment.
May the code change to this below due to  [54](https://github.com/theicfire/makefiletutorial/issues/54)? 
```shell
obj_files = foo.result bar.o lose.o
src_files = foo.raw bar.c lose.c

all: $(obj_files)

$(filter %.o,$(obj_files)): %.o: %.c
	cc -c $< -o $@
	echo "target: $@ prereq: $<"
$(filter %.result,$(obj_files)): %.result: %.raw
	cc -c $< -o $@
	echo "target: $@ prereq: $<" 

$(src_files):
	touch $@

clean:
	rm -f $(src_files) $(obj_files)
```

But unfortunately, the implicit rule failed to work in this example, and no `X.result` file is generated.

**Comment by chaselambda** [comment]
Thanks! Yeah it looks like I need the `.PHONY: all` in this example. Fixed here: https://github.com/theicfire/makefiletutorial/commit/e7a44a1dd78db663b55b014b5c8a524cb9dcc92a

I don't need to explicitly run the `cc` commands like you've shown, because I don't even need output in this example.
