### ISSUE TITLE
Cookbook string substitution

### ISSUE THREAD

**Issue by zupatisc** [chaselambda/makefiletutorial#66]
Hi, thank you very much for the tutorial,

I am trying to adapt the cookbook so that object files are put into a seperate obj directory.
The following section gives me trouble:
```
# Find all the C and C++ files we want to compile
# Note the single quotes around the * expressions. Make will incorrectly expand these otherwise.
SRCS := $(shell find $(SRC_DIRS) -name '*.cpp' -or -name '*.c' -or -name '*.s')

# String substitution for every C/C++ file.
# As an example, hello.cpp turns into ./build/hello.cpp.o
OBJS := $(SRCS:%=$(BUILD_DIR)/%.o)
```
The example you give here for what the substitution does seems correct but given that SRCS is not of the format 'hello.cpp' but rather './src/hello.cpp' the output will be 'BUILD_DIR/./src/hello.cpp' and this of course applies to my attempts at having all object files in another directory as well.
Aside from this being (IMO) ugly it also, considering the mismatch between the example and what happens, seems rather unintended.

**Comment by chaselambda** [comment]
Thank you for the message. What's your suggested change? Just update the comment, or something else?

**Comment by zupatisc** [comment]
I would suggest changing the subsitution to
`OBJS := $(SRCS:$(SRC_DIRS)/%.c=$(BUILD_DIR)/%.o)`
for me the results in the desired `./BUILD_Dir/hello.o` path.

**Comment by chaselambda** [comment]
I see, your suggestion isn't general enough in that it doesn't support `.cpp` and `.s` files. I think just changing the comment should be sufficient. Fixed!
