### ISSUE TITLE
Add small caveat about compilation for pedantic JavaScript developers

### ISSUE THREAD

**Issue by sebastiancarlos** [chaselambda/makefiletutorial#71]
I would propose this addition **(in bold)**:

> Interpreted languages like Python, Ruby, and Javascript don't require an analogue to Makefiles. The goal of Makefiles is to compile whatever files need to be compiled, based on what files have changed. But when files in interpreted languages change, nothing needs to get recompiled. When the program runs, the most recent version of the file is used. **(There are some exceptions, like transpiling Typescript files to Javascript)**

**Comment by chaselambda** [comment]
Fixed in a slightly different way, thank you!
