### ISSUE TITLE
Mobile version of the site has no side margins

### ISSUE THREAD

**Issue by FireIsGood** [chaselambda/makefiletutorial#76]
In the mobile (and technically the desktop) versions of the site, there is no inline margin. This makes it annoying to read as the text goes all the way to the edge of the page.

Here's an example from the developer tools:

![image](https://github.com/theicfire/makefiletutorial/assets/109556932/5109d92b-7242-4e06-8cac-38adeb5d9f89)

This could be solved by adding a `1em` or so inline margin on the main element. I feel this would improve the reading experience for mobile users.

**Comment by chaselambda** [comment]
Turns out there was already 8px padding but I now doubled it, thanks!
