### ISSUE TITLE
Automatic pattern $< is used but never explained

### ISSUE THREAD

**Issue by FireIsGood** [chaselambda/makefiletutorial#77]
The automatic pattern `$<` is used in [Static Pattern Rules and Filter](https://makefiletutorial.com/#static-pattern-rules-and-filter) and the [Makefile Cookbook](https://makefiletutorial.com/#makefile-cookbook) but never explained in the [Automatic Variables](https://makefiletutorial.com/#automatic-variables) section directly.

The pattern `$?` is explained in Automatic variables but is never used later. I think that `$<` should be explained with the other automatic variables if it is used in the final cookbook example.

**Comment by chaselambda** [comment]
Great call, fixed and thank you! https://github.com/theicfire/makefiletutorial/commit/8bb4d1f43998a2ffc3f0f82fd7bd6e0362bbd93d
