### ISSUE TITLE
It's necessary to explain pattern matching priority

### ISSUE THREAD

**Issue by HaoliangXu** [chaselambda/makefiletutorial#83]
In "Static Pattern Rules", both "all.c" and "%.c" could match "all.c"
Readers(Including me a few minutes ago) may wonder which one will be matched, or if both, which one would be the first.
So I think pattern matching priority should be explained.

**Comment by chaselambda** [comment]
Fixed, thanks! https://github.com/theicfire/makefiletutorial/commit/ff2ad79af1b16e37e0e9a6d6e12d7c3dbb4a40a1
