### ISSUE TITLE
Section 4.10

### ISSUE THREAD

**Issue by llitfkitfk** [chaselambda/makefiletutorial#9]
find some bugs: 
all: $(obj_files) ->  all: $(src_files)
touch %@ -> touch $@

**Comment by chaselambda** [comment]
The first one isn't a bug, the second is and is now fixed. Thank you!

**Comment by chaselambda** [comment]
For clarity: we want to "build" the object files. If we were trying to create the src_files, they would just be generated but nothing else would run.
